/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package potdar.aishwarya.ui;

import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.UIManager;
import potdar.aishwarya.business.BatchInfo;
import potdar.aishwarya.business.Database;
import potdar.aishwarya.business.ModuleInfo;
import potdar.aishwarya.business.StudentFilter;
import potdar.aishwarya.business.StudentInfo;

/**
 *
 * @author soleg
 */
public class MainDialog extends javax.swing.JDialog {
    private static MainDialog instance = null;
    private StudentFilter filter = new StudentFilter();

    /**
     * Creates new form MainDialog
     */
    public MainDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        instance = this;
        initComponents();
        this.setResizable(false);
        loadStudentList();
        loadBatchList();
        loadModuleList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        imagePanel1 = new potdar.aishwarya.ui.ImagePanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        studentFilterTextField = new javax.swing.JTextField();
        moduleFilterCombo = new javax.swing.JComboBox();
        batchFilterCombo = new javax.swing.JComboBox();
        feesNotPaidChk = new javax.swing.JCheckBox();
        feesPaidChk = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentListPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        batchListPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        moduleListPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Glorious Students");
        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(884, 600));

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(805, 175));

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Welcome", jPanel6);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 147));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filter"));

        studentFilterTextField.setPreferredSize(null);
        studentFilterTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentFilterTextFieldKeyReleased(evt);
            }
        });

        moduleFilterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleFilterComboActionPerformed(evt);
            }
        });

        batchFilterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchFilterComboActionPerformed(evt);
            }
        });

        feesNotPaidChk.setText("Fees Not Paid");
        feesNotPaidChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesNotPaidChkActionPerformed(evt);
            }
        });

        feesPaidChk.setText("Fees Paid");
        feesPaidChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesPaidChkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentFilterTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(moduleFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(batchFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(feesPaidChk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feesNotPaidChk)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentFilterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moduleFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batchFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feesNotPaidChk)
                    .addComponent(feesPaidChk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout studentListPanelLayout = new javax.swing.GroupLayout(studentListPanel);
        studentListPanel.setLayout(studentListPanelLayout);
        studentListPanelLayout.setHorizontalGroup(
            studentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        studentListPanelLayout.setVerticalGroup(
            studentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(studentListPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Students", jPanel1);

        javax.swing.GroupLayout batchListPanelLayout = new javax.swing.GroupLayout(batchListPanel);
        batchListPanel.setLayout(batchListPanelLayout);
        batchListPanelLayout.setHorizontalGroup(
            batchListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        batchListPanelLayout.setVerticalGroup(
            batchListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(batchListPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Batches", jPanel2);

        javax.swing.GroupLayout moduleListPanelLayout = new javax.swing.GroupLayout(moduleListPanel);
        moduleListPanel.setLayout(moduleListPanelLayout);
        moduleListPanelLayout.setHorizontalGroup(
            moduleListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        moduleListPanelLayout.setVerticalGroup(
            moduleListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(moduleListPanel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modules", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentFilterTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentFilterTextFieldKeyReleased
        updateStudentFilter();
    }//GEN-LAST:event_studentFilterTextFieldKeyReleased

    private void moduleFilterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleFilterComboActionPerformed
        updateStudentFilter();
        loadFilterBatch();
    }//GEN-LAST:event_moduleFilterComboActionPerformed

    private void batchFilterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchFilterComboActionPerformed
        updateStudentFilter();
    }//GEN-LAST:event_batchFilterComboActionPerformed

    private void feesPaidChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesPaidChkActionPerformed
        updateStudentFilter();
    }//GEN-LAST:event_feesPaidChkActionPerformed

    private void feesNotPaidChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesNotPaidChkActionPerformed
        updateStudentFilter();
    }//GEN-LAST:event_feesNotPaidChkActionPerformed

    private void updateStudentFilter() {
        if (batchFilterCombo.getSelectedIndex() > 0)
            filter.setBatchId(Database.getFilteredBatchList(filter).get(batchFilterCombo.getSelectedIndex()-1).getId());
        if (moduleFilterCombo.getSelectedIndex() > 0)
            filter.setModuleId(Database.getModuleList().get(moduleFilterCombo.getSelectedIndex()-1).getId());
        if (feesNotPaidChk.isSelected() && feesPaidChk.isSelected()){
            filter.setFeesNotPaid(false);
            filter.setFeesPaid(false);
        } else {
            filter.setFeesNotPaid(feesNotPaidChk.isSelected());
            filter.setFeesPaid(feesPaidChk.isSelected());
        }
        filter.setName(studentFilterTextField.getText());
        loadStudentList();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainDialog dialog = new MainDialog(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void loadStudentList() {
        studentListPanel.removeAll();
        studentListPanel.setLayout(new BoxLayout(studentListPanel, BoxLayout.Y_AXIS));
        StudentPanel p = new StudentPanel();
        studentListPanel.add(p);
        for (StudentInfo s : Database.getStudentList(filter)) {
            p = new StudentPanel();
            p.setInfo(s);
            studentListPanel.add(p);
        }
        studentListPanel.revalidate();
        studentListPanel.repaint();
        jScrollPane1.getVerticalScrollBar().setValue(0);
    }
    
    private void loadFilterBatch() {
        System.out.println("loadFilterBatchModule");
        batchFilterCombo.removeAllItems();
        batchFilterCombo.addItem("All Batches");
        for(BatchInfo b : Database.getFilteredBatchList(filter))
            batchFilterCombo.addItem(b);
    }

    public static void refreshStudentList() {
        instance.filter = new StudentFilter();
        instance.loadStudentList();
    }

    private void loadBatchList() {
        batchListPanel.removeAll();
        batchListPanel.setLayout(new BoxLayout(batchListPanel, BoxLayout.Y_AXIS));
        BatchPanel p = new BatchPanel();
        batchListPanel.add(p);
        for (BatchInfo s : Database.getBatchList()) {
            p = new BatchPanel();
            p.setBatchInfo(s);
            batchListPanel.add(p);
        }
        batchListPanel.revalidate();
        batchListPanel.repaint();
    }

    public static void refreshBatchList() {
        instance.loadBatchList();
        instance.loadStudentList();
    }

    private void loadModuleList() {
        moduleListPanel.removeAll();
        moduleListPanel.setLayout(new BoxLayout(moduleListPanel, BoxLayout.Y_AXIS));
        ModulePanel p = new ModulePanel();
        moduleListPanel.add(p);
        for (ModuleInfo s : Database.getModuleList()) {
            p = new ModulePanel();
            p.setModuleInfo(s);
            moduleListPanel.add(p);
        }
        moduleListPanel.revalidate();
        moduleListPanel.repaint();
        moduleFilterCombo.addItem("All Modules");
        for(ModuleInfo m : Database.getModuleList())
            moduleFilterCombo.addItem(m);
        loadFilterBatch();
    }

    public static void refreshModuleList() {
        instance.loadModuleList();
        instance.loadBatchList();
        instance.loadStudentList();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox batchFilterCombo;
    private javax.swing.JPanel batchListPanel;
    private javax.swing.JCheckBox feesNotPaidChk;
    private javax.swing.JCheckBox feesPaidChk;
    private potdar.aishwarya.ui.ImagePanel imagePanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox moduleFilterCombo;
    private javax.swing.JPanel moduleListPanel;
    private javax.swing.JTextField studentFilterTextField;
    private javax.swing.JPanel studentListPanel;
    // End of variables declaration//GEN-END:variables
}
